### PR TITLE
build: add Dockerfile

### PR DESCRIPTION
**Pull request by PaulBernier**
Add a Docker file to build a fatd Docker image based on alpine 3.9

### CODE REVIEW

**Comment by AdamSLevy** [comment]
As a start this looks good. Thank you. I'm going to merge it.

Some thoughts on possible improvements that I'd like to hear your opinion on.

Does it make sense to also install `fat-cli` in the container? It could be used by someone who wants to mess with fatd from a shell inside the container.

Does it make sense to also install bash completion for `fatd` (and `fat-cli` if installed)? If you get a shell in the container it would be helpful.

Would it ever make any sense to create a container that bundles factomd in the container?

**Comment by AdamSLevy** [comment]
Oh does the `docker run` command need options to expose the fatd API port?

**Comment by PaulBernier** [comment]
Good questions, I am not a Docker expert so I will answer to the best of my knowledge, I will try to ask Jay C. if he can give us his perspective too.

1. I remember back on the early testnet days the factomd container was packed with a factom-cli. I personally didn't find it practical, mostly because I could never remember by heart the lengthy docker command required to get the shell session... It had a fair use in tutorials though, where the use could copy paste the whole command. I am  wondering if it is a common/best practice to put CLIs in Docker containers, as to me the point of Docker is to rather run services than command line tools. 

2. I am not sure how fatd completion could work though? Because the completion should happen at the end of the `docker run` command, not sure it is possible, as it is a command outside of the container. 

3. If we decide to add the `fat-cli` inside the container then yes adding autocompletion for it makes sense.

4. I believe that Docker philosophy is to have one container per service. `fatd` is a service, `factomd` is an independent service, they should live in separate containers. For instance usually you will have a `postgres` container running independently rather than having postgres directly bundled in the same container as your app. [This is what Factom Open API did for instance.](https://github.com/DeFacto-Team/Factom-Open-API/blob/master/guides/INSTALL_DOCKER.md#option-1-run-postgres-db-into-docker-container)

5. In the readme I used the flag `--network=host` for the `docker run` command, for the container to be able to access a `factomd` instance running on localhost. With the host network, ports are automatically exposed so nothing else would be required. If you don't use the host network then you would need to use `-p 8078:8078` to expose the fatd API.

**Comment by AdamSLevy** [comment]
1. Seems like it wouldn't hurt to include it but I agree that most of the time a user will not want to get a prompt inside the container and run commands from there. but if I did I'd want fat-cli to be there.

2. I was only referring to completion within the container. not fatd completion for the end of the docker run command. Again I agree that this is of very limited utility. How often would a user need completion to invoke fatd from within the container? probably not often, maybe not ever.

3. same as 2 pretty much.

4. Makes sense. thanks for explaining that.

5. OK. that works. people who use docker presumably would know to do that.

**Comment by jcheroske** [comment]
Hi all. Paul reached out to me the other day about this discussion you're having. Here are some of my thoughts:

1. One major process per container is the correct philosophy, so putting fatd and factomd in the same container would be a mistake.

2. Dropping the CLI in the image is probably a good thing and shouldn't negatively impact anything.

3. Shelling into containers for all kinds of reasons is really common. Command completion might be a bit overkill (but not out of the question) but making the container easy to understand and use from the inside is a huge plus.

4. The pattern for getting a shell looks like:
  * Running container: `docker exec -it container_name /bin/sh`
  * New container: `docker run -it foo/bar:tag /bin/sh` or `docker run -it --entrypoint /bin/sh foo/bar:tag` depending on how the image is structured.

5. Multistage builds are your friend. They allow you to create intermediate images in which you can do work and then copy that work into your final image. For example, you could build your Go binary in one image, and copy the final product into an Alpine image. The build image would be discarded:
```
FROM golang:alpine AS build
COPY your assets into the image
RUN go to build your project

FROM alpine
COPY --from=build /go/bin/fatd /path/to/fatd
ENTRYPOINT /path/to/fatd
```
This simple example would result in an Alpine image that only had your `fatd` binary in it. All of the Go build stuff would be discarded. The resulting image would be very small, which is nice.

6. You shouldn't run your daemon process as root. You'll want to create a non-root user and then switch to that user before running fatd.

Putting this all together, here is a quick crack at a Dockerfile for your project. Not tested!
```
FROM golang:alpine AS build

WORKDIR /go/src

COPY your_source_code .

RUN the_go_build

FROM alpine:latest

WORKDIR /home/app # <-- I'm a fan of putting everything under here

COPY --from=build /go/bin/fatd .
COPY --from=build /go/bin/fat-cli .

RUN set -xe && \
  apk add --no-cache shadow && \
  groupadd -g 1000 app && \
  useradd -r -m -u 1000 -g app app && \
  chown -R app:app .

USER app

VOLUME /home/app/config

ENTRYPOINT ["./fatd"]

CMD ["command", "args", "go", "here"]
```
Hope that is useful.

**Comment by PaulBernier** [comment]
Thanks @jcheroske for chiming in. About 6, I did try to use a non root user to start fatd but I hit a blocker when trying to mount the volume storing the fatd db (when running `docker run -v "fatd_db:/fatd.db"` as it seems the volume mounted is necessarily owned by root. Is that what your command `VOLUME /home/app/config` could help solve? What does this command does here exactly?

Otherwise it looks pretty much like what I did in this PR.

**Comment by jcheroske** [comment]
`VOLUME` isn't really necessary. You can read about it here: https://docs.docker.com/engine/reference/builder/#volume. It's mostly just for self-documentation. The `EXPOSE` command is kinda similar in that way. 

I didn't actually look at the files in this PR before I started ranting! I'm glad we're thinking along the same lines.

As for the permission problem when running as non-root, I haven't run into that. I've run locally and on k8s, and everything has worked fine for me. The uid of the user you create inside the container is the same uid that the container will run as on the host system. So, if you created a uid 1000 user inside your container, it will run as uid 1000 on the host. If you grant permissions to that uid or start the container with a different uid (--user flag) you should be able to get things working. This explains all that: https://medium.com/@mccode/understanding-how-uid-and-gid-work-in-docker-containers-c37a01d01cf

**Comment by jcheroske** [comment]
Can you post a sample config file? I'm curious about its format and content.

**Comment by PaulBernier** [comment]
There is no config file. The volume created is for persisting the database created by fatd. Similar to the setup we have for factomd.

**Comment by jcheroske** [comment]
So there's no config file at all? How do you tell `fatd` where to find its factomd backend for instance?

**Comment by drkatz** [comment]
@jcheroske With the use of [flags](https://github.com/Factom-Asset-Tokens/fatd#startup-flags--options) during startup of fatd from the command line

**Pull request merged**
